openapi: 3.0.1
info:
  title: Sample API
  description: API for demonstrating OpenAPI Generator
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a greeting message
      operationId: getGreeting
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string